#!/usr/bin/env -S npx tsx
/**
 * push-source — push bookmark sources into bookmark-digest without the web app.
 *
 *   push-source extract <url> [--out <file>]
 *       Fetch a YouTube transcript into a .md file (default: a timestamped file
 *       in the current directory). Prints the path to stdout.
 *
 *   push-source create <file> --url <url> [--content-type <type>]
 *       POST the file's contents to POST /sources. `--url` is required unless the
 *       file already carries a `**Source:** <url>` line. content-type defaults to
 *       "unknown"; pass "video" for transcripts.
 *
 *   push-source login
 *       Force a fresh Cognito login and store the token locally.
 *
 *       Clear the cached Cognito token.
 *
 *   Config (apps/infra/outputs.json, regenerated by `pnpm outputs`):
 *     ApiUrl                API Gateway base URL (cdk output)
 *     CliUserPoolClientId   CLI Cognito client id (cdk output)
 *
 *   Config (env — optional overrides, otherwise read from outputs.json):
 *     BKDG_EMAIL       cached Cognito email
 *     BKDG_PASSWORD    avoids the interactive password prompt
 */

import "dotenv/config";
import * as fs from "node:fs";
import * as path from "node:path";
import {
  fetchYouTubeTranscript,
  formatYouTubeSource,
  parseYouTubeVideoId,
} from "../lib/youtube";
import {
  getCredential,
  login as cognitoLogin,
  logout as cognitoLogout,
  loadCognitoConfig,
} from "../lib/cognito-auth";
import { apiBaseUrl } from "../lib/stack-outputs";

const VALID_CONTENT_TYPES = ["article", "video", "unknown"] as const;

const USAGE = `push-source — push bookmark sources into bookmark-digest.

Usage:
  push-source extract <url> [--out <file>]     Fetch a YouTube transcript into a .md file
  push-source create <file> --url <url> [--content-type <type>]
                                               POST the file as a source
  push-source login                            Force a fresh Cognito login (stores token)
  push-source logout                           Clear the cached Cognito token`;

interface ParsedArgs {
  positionals: string[];
  flags: Record<string, string>;
}

/** Minimal `--flag value` / positional arg parser. */
function parseArgs(argv: string[]): ParsedArgs {
  const positionals: string[] = [];
  const flags: Record<string, string> = {};
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    if (arg.startsWith("--")) {
      const key = arg.slice(2);
      const next = argv[i + 1];
      if (next === undefined || next.startsWith("--")) {
        flags[key] = "true";
      } else {
        flags[key] = next;
        i++;
      }
    } else {
      positionals.push(arg);
    }
  }
  return { positionals, flags };
}

function normalizeContentType(value: string | undefined): (typeof VALID_CONTENT_TYPES)[number] | null {
  if (!value) return "unknown";
  return (VALID_CONTENT_TYPES as readonly string[]).includes(value)
    ? (value as (typeof VALID_CONTENT_TYPES)[number])
    : null;
}

/** Recover a stored source URL from a `**Source:** <url>` line in the file. */
function detectSourceUrl(content: string): string | null {
  const match = content.match(/\*\*Source:\*\*\s+(\S+)/i);
  return match ? match[1] : null;
}

async function cmdExtract(url: string, out: string | undefined): Promise<number> {
  const videoId = parseYouTubeVideoId(url);
  if (!videoId) {
    console.error(`Not a recognizable YouTube URL: ${url}`);
    return 1;
  }

  console.error(`Fetching transcript for ${videoId}…`);
  const result = await fetchYouTubeTranscript(videoId);
  if (!result) {
    console.error(
      "No transcript available. The video may have none, or this network is being " +
        "refused by YouTube's captions endpoint — try again later or from a different network.",
    );
    return 1;
  }

  const markdown = formatYouTubeSource(result);
  const dest = out ?? path.join(process.cwd(), `bookmark-digest-source-${Date.now()}.md`);
  fs.writeFileSync(dest, markdown, "utf8");

  console.error(
    `Fetched ${result.transcript.length} chars, lang=${result.languageCode}, ` +
      `autoGenerated=${result.autoGenerated}`,
  );
  console.log(dest);
  return 0;
}

async function cmdCreate(
  file: string,
  url: string | undefined,
  contentType: string | undefined,
): Promise<number> {
  if (!fs.existsSync(file)) {
    console.error(`File not found: ${file}`);
    return 1;
  }
  const content = fs.readFileSync(file, "utf8").trim();
  if (!content) {
    console.error(`File is empty: ${file}`);
    return 1;
  }

  const sourceUrl = url ?? detectSourceUrl(content);
  if (!sourceUrl) {
    console.error(
      "No URL to store. Pass --url <url>, or add a `**Source:** <url>` line to the file.",
    );
    return 1;
  }

  const resolvedType = normalizeContentType(contentType);
  if (!resolvedType) {
    console.error(
      `Invalid --content-type: ${contentType}. Use one of: ${VALID_CONTENT_TYPES.join(", ")}.`,
    );
    return 1;
  }

  const config = loadCognitoConfig();
  const credential = await getCredential(config);
  if (!credential.idToken) {
    console.error("No ID token available.");
    return 1;
  }

  const apiBase = apiBaseUrl();

  const res = await fetch(`${apiBase.replace(/\/+$/, "")}/sources`, {
    method: "POST",
    headers: { "Content-Type": "application/json", Authorization: credential.idToken },
    body: JSON.stringify({ url: sourceUrl, content, contentType: resolvedType }),
  });

  let json: { error?: unknown; sourceHash?: string; status?: string } | null = null;
  try {
    json = (await res.json()) as { error?: unknown; sourceHash?: string; status?: string };
  } catch {
    // Non-JSON error body; fall through to res.statusText below.
  }

  if (!res.ok) {
    const message = json?.error ? String(json.error) : res.statusText;
    console.error(`POST /sources failed (${res.status}): ${message}`);
    return 1;
  }

  console.log(
    JSON.stringify({ sourceHash: json?.sourceHash, status: json?.status, contentType: resolvedType, url: sourceUrl }),
  );
  return 0;
}

async function main(): Promise<number> {
  const [name, ...rest] = process.argv.slice(2);
  const { positionals, flags } = parseArgs(rest);

  try {
    switch (name) {
      case "extract": {
        const [url] = positionals;
        if (!url) {
          console.error("Usage: push-source extract <url> [--out <file>]");
          return 1;
        }
        return await cmdExtract(url, flags.out ?? undefined);
      }
      case "create": {
        const [file] = positionals;
        if (!file) {
          console.error("Usage: push-source create <file> --url <url> [--content-type <type>]");
          return 1;
        }
        return await cmdCreate(file, flags.url ?? undefined, flags["content-type"] ?? undefined);
      }
      case "login": {
        const config = loadCognitoConfig();
        const credential = await cognitoLogin(config);
        console.log(`Logged in as ${credential.email} (cached=${credential.cached}).`);
        return 0;
      }
      case "logout": {
        cognitoLogout();
        console.log("Cleared cached Cognito token.");
        return 0;
      }
      default: {
        console.log(USAGE);
        return name ? 1 : 0;
      }
    }
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    console.error(message);
    return 1;
  }
}

main().then((code) => {
  process.exitCode = code;
});
