#!/usr/bin/env -S npx tsx
/**
 * YouTube transcript fetcher — CLI, run by hand.
 *
 * This used to run inside the ingest-url Lambda. It was pulled out because it
 * doesn't work reliably from there: YouTube's InnerTube captions endpoint
 * silently omits caption tracks (200 OK, no error) for a large share of
 * requests from Lambda's shared/datacenter IP ranges, while working fine from
 * a residential IP. That isn't fixable from our side, so the automatic path
 * is gone (see plans/thin-source-detection.md) and this is the replacement:
 * run it from your own machine, paste the output into the web app's "Paste
 * text instead of fetching" box.
 *
 * Usage:
 *   npx tsx scripts/youtube-transcript.ts <youtube-url> [lang]
 *
 * Prints the formatted markdown to stdout; nothing else goes to stdout, so
 * `> transcript.md` or piping to `pbcopy` both work.
 */
import {
  formatYouTubeSource,
  fetchYouTubeTranscript,
  parseYouTubeVideoId,
} from "../lib/youtube";

async function main() {
  const [rawUrl, lang] = process.argv.slice(2);
  if (!rawUrl) {
    console.error("Usage: npx tsx scripts/youtube-transcript.ts <youtube-url> [lang]");
    process.exitCode = 1;
    return;
  }

  const videoId = parseYouTubeVideoId(rawUrl);
  if (!videoId) {
    console.error(`Not a recognizable YouTube video URL: ${rawUrl}`);
    process.exitCode = 1;
    return;
  }

  const result = await fetchYouTubeTranscript(videoId, lang ?? "en");
  if (!result) {
    console.error(
      `No transcript available for ${videoId}. Either the video has no captions, or this ` +
        `network is currently being refused by YouTube's captions endpoint — try again later ` +
        `or from a different network.`
    );
    process.exitCode = 1;
    return;
  }

  console.error(
    `Fetched ${result.transcript.length} chars, lang=${result.languageCode}, ` +
      `autoGenerated=${result.autoGenerated}`
  );
  process.stdout.write(formatYouTubeSource(result));
  process.stdout.write("\n");
}

main();
