/**
 * YouTube transcript extraction — shared between the standalone
 * `scripts/youtube-transcript.ts` CLI and the `push-source extract` subcommand
 * of `scripts/push-source.ts`.
 *
 * This used to run inside the ingest-url Lambda. It was pulled out because it
 * doesn't work reliably from there: YouTube's InnerTube captions endpoint
 * silently omits caption tracks (200 OK, no error) for a large share of
 * requests from Lambda's shared/datacenter IP ranges, while working fine from
 * a residential IP. That isn't fixable from our side, so the automatic path is
 * gone (see plans/source-quality-and-upload.md) and these run on the user's own
 * machine.
 */

const PLAYER_URL = "https://youtubei.googleapis.com/youtubei/v1/player?prettyPrint=false";

/**
 * InnerTube clients, tried in order. Which clients are served caption tracks
 * changes without notice, and a client that is refused returns a 200 with the
 * captions key simply absent rather than an error — so "no tracks" is not a
 * reliable signal that the video has no captions until every client has been
 * tried.
 */
const CLIENTS = [
  {
    name: "iOS",
    nameHeader: "5",
    version: "20.10.4",
    userAgent: "com.google.ios.youtube/20.10.4 (iPhone16,2; U; CPU iOS 18_3_2 like Mac OS X;)",
    extra: {
      deviceMake: "Apple",
      deviceModel: "iPhone16,2",
      osName: "iPhone",
      osVersion: "18.3.2.22D82",
    },
  },
  {
    name: "ANDROID_VR",
    nameHeader: "28",
    version: "1.62.20",
    userAgent:
      "com.google.android.apps.youtube.vr.oculus/1.62.20 (Linux; U; Android 12L; eureka-user Build/SQ3A.220605.009.A1) gzip",
    extra: {
      deviceMake: "Oculus",
      deviceModel: "Quest 3",
      osName: "Android",
      osVersion: "12L",
      androidSdkVersion: 32,
    },
  },
  {
    name: "MWEB",
    nameHeader: "2",
    version: "2.20251209.01.00",
    userAgent:
      "Mozilla/5.0 (iPhone; CPU iPhone OS 17_5_1 like Mac OS X) AppleWebKit/605.1.15",
    extra: {},
  },
] as const;

const YOUTUBE_HOSTS = new Set([
  "youtube.com",
  "www.youtube.com",
  "m.youtube.com",
  "music.youtube.com",
  "youtube-nocookie.com",
  "www.youtube-nocookie.com",
  "youtu.be",
  "www.youtu.be",
]);

/** A YouTube video id is exactly 11 chars of the base64url alphabet. */
const VIDEO_ID_RE = /^[A-Za-z0-9_-]{11}$/;

/** Path prefixes that carry the video id as the next path segment. */
const ID_BEARING_PREFIXES = ["shorts", "live", "embed", "v"];

interface CaptionTrack {
  baseUrl: string;
  languageCode: string;
  /** Present ("asr") on auto-generated tracks, absent on human-authored ones. */
  kind?: string;
}

interface VideoDetails {
  title?: string;
  author?: string;
  shortDescription?: string;
  lengthSeconds?: string;
}

export interface YouTubeTranscript {
  videoId: string;
  transcript: string;
  details: VideoDetails;
  /** Language of the track actually used, for logging. */
  languageCode: string;
  /** True when the only track available was auto-generated captions. */
  autoGenerated: boolean;
}

// The InnerTube player + caption-track endpoints return untrusted JSON of an
// unstable shape. Type the known surface with `unknown` at the boundary and
interface InnerTubePlayer {
  videoDetails?: {
    title?: string;
    author?: string;
    shortDescription?: string;
    lengthSeconds?: string;
  };
  captions?: {
    playerCaptionsTracklistRenderer?: {
      captionTracks?: CaptionTrack[];
    };
  };
}

interface TranscriptEvent {
  segs?: { utf8?: string }[];
}

interface CaptionTrackJson {
  events?: TranscriptEvent[];
}

/**
 * Extracts the video id from any YouTube URL shape, or returns null if the URL
 * is not a YouTube video.
 */
export function parseYouTubeVideoId(rawUrl: string): string | null {
  let parsed: URL;
  try {
    parsed = new URL(rawUrl);
  } catch {
    return null;
  }

  if (!YOUTUBE_HOSTS.has(parsed.hostname.toLowerCase())) return null;

  const v = parsed.searchParams.get("v");
  if (v && VIDEO_ID_RE.test(v)) return v;

  const segments = parsed.pathname.split("/").filter(Boolean);
  if (segments.length === 0) return null;

  if (parsed.hostname.toLowerCase().endsWith("youtu.be")) {
    return VIDEO_ID_RE.test(segments[0]) ? segments[0] : null;
  }

  if (ID_BEARING_PREFIXES.includes(segments[0]) && segments[1] && VIDEO_ID_RE.test(segments[1])) {
    return segments[1];
  }

  return null;
}

async function fetchPlayer(videoId: string, client: (typeof CLIENTS)[number]): Promise<unknown> {
  const res = await fetch(PLAYER_URL, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Accept: "*/*",
      "User-Agent": client.userAgent,
      "X-YouTube-Client-Name": client.nameHeader,
      "X-YouTube-Client-Version": client.version,
      Origin: "https://www.youtube.com",
    },
    body: JSON.stringify({
      videoId,
      context: {
        client: {
          clientName: client.name,
          clientVersion: client.version,
          hl: "en",
          gl: "US",
          ...client.extra,
        },
        user: { lockedSafetyMode: false },
        request: { useSsl: true },
      },
      contentCheckOk: true,
      racyCheckOk: true,
    }),
  });
  if (!res.ok) throw new Error(`InnerTube player returned ${res.status}`);
  return res.json();
}

/**
 * Prefers a human-authored track in the requested language, then any track in
 * that language (i.e. auto-generated), then any regional variant of it, and
 * finally whatever exists — a transcript in the wrong language still beats
 * scraped page chrome.
 */
function pickTrack(tracks: CaptionTrack[], lang: string): CaptionTrack {
  return (
    tracks.find((t) => t.languageCode === lang && !t.kind) ??
    tracks.find((t) => t.languageCode === lang) ??
    tracks.find((t) => t.languageCode.startsWith(lang)) ??
    tracks[0]
  );
}

function decodeHtml(str: string): string {
  return str
    .replace(/<[^>]*>/g, "")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    // &amp; last, so "&amp;lt;" decodes to "&lt;" rather than "<".
    .replace(/&amp;/g, "&");
}
/**
 * The player response is untrusted, unstable-shape JSON. This keeps the shape
 * closed to what we read (`videoDetails`, `captions`) so callers can index it
 * without an `any` escape hatch.
 */
function isInnerTubePlayer(value: unknown): value is InnerTubePlayer {
  return (
    typeof value === "object" &&
    value !== null &&
    ("videoDetails" in value || "captions" in value)
  );
}

/**
 * Fetches the transcript and video metadata for a YouTube video id.
 * Returns null when no caption track can be obtained — the video has none, or
 * YouTube has changed the endpoint again, or (see the module comment) this
 * particular network is currently being refused.
 */
export async function fetchYouTubeTranscript(
  videoId: string,
  lang = "en"
): Promise<YouTubeTranscript | null> {
  let tracks: CaptionTrack[] | undefined;
  let details: VideoDetails = {};

  for (const client of CLIENTS) {
    try {
      const raw = await fetchPlayer(videoId, client);
      if (!isInnerTubePlayer(raw)) continue;
      if (!details.title && raw.videoDetails) {
        details = raw.videoDetails;
      }
      const found = raw.captions?.playerCaptionsTracklistRenderer?.captionTracks;
      if (Array.isArray(found) && found.length > 0) {
        tracks = found;
        break;
      }
    } catch (err) {
      console.error(`InnerTube client ${client.name} failed for ${videoId}:`, err);
    }
  }

  if (!tracks?.length) return null;

  const track = pickTrack(tracks, lang);
  let transcript: string;
  try {
    const res = await fetch(`${track.baseUrl}&fmt=json3`);
    const parsed = (await res.json()) as CaptionTrackJson;
    const events = Array.isArray(parsed.events) ? parsed.events : [];
    transcript = events
      .filter((e): e is TranscriptEvent & { segs: { utf8?: string }[] } => Array.isArray(e.segs))
      .map((e) => e.segs.map((s) => decodeHtml(s.utf8 ?? "")).join(""))
      .join(" ")
      .replace(/\s+/g, " ")
      .trim();
  } catch (err) {
    console.error(`Caption track fetch failed for ${videoId}:`, err);
    return null;
  }

  if (!transcript) return null;

  return {
    videoId,
    transcript,
    details,
    languageCode: track.languageCode,
    autoGenerated: Boolean(track.kind),
  };
}

/**
 * Renders a transcript as the markdown to paste into the web app's source
 * form. The transcript alone is a wall of unattributed speech with no title,
 * so the metadata header is not decoration: it is where the generator learns
 * the talk's title, who is speaking, and the author's own framing of it.
 */
export function formatYouTubeSource(result: YouTubeTranscript): string {
  const { details, videoId, transcript, autoGenerated } = result;
  const lines: string[] = [];

  lines.push(`# ${details.title ?? "Untitled YouTube video"}`);
  lines.push("");
  if (details.author) lines.push(`**Channel:** ${details.author}`);
  if (details.lengthSeconds) {
    const total = Number(details.lengthSeconds);
    if (Number.isFinite(total) && total > 0) {
      const mins = Math.floor(total / 60);
      const secs = String(total % 60).padStart(2, "0");
      lines.push(`**Duration:** ${mins}:${secs}`);
    }
  }
  lines.push(`**Source:** https://www.youtube.com/watch?v=${videoId}`);
  lines.push("");

  const description = details.shortDescription?.trim();
  if (description) {
    lines.push("## Description");
    lines.push("");
    lines.push(description);
    lines.push("");
  }

  lines.push("## Transcript");
  lines.push("");
  if (autoGenerated) {
    lines.push(
      "_Auto-generated captions. Proper nouns and technical terms may be transcribed incorrectly._"
    );
    lines.push("");
  }
  lines.push(transcript);

  return lines.join("\n");
}
